name: LaravelPrac
recipe: laravel
config:
  webroot: ./public
  php: "8.4"
  via: apache
  database: mariadb:11.4.4
  cache: redis

services:
  appserver:
    type: php:8.4
    build_as_root:
      - curl -sS https://getcomposer.org/installer | php -- --version=2.8.8 --install-dir=/usr/local/bin --filename=composer
    overrides:
      environment:
        PATH: "/usr/local/bin:$PATH"

  database:
    type: mariadb:11.4.4
    portforward: true
    creds:
      user: laravel
      database: laravel
    config:
      databases:
        - laravel
      user: laravel
      default: laravel

  phpmyadmin:
    type: phpmyadmin
    ssl: true
    hosts:
      - database
    config:
      host: database
      user: laravel
      verbose: true
