name: pracapp
recipe: laravel
config:
  webroot: ./public
  php: "8.4"
  via: apache
  database: mariadb:11.4.4
  cache: redis

services:
  database:
    type: mariadb:11.4.4
    portforward: true
    creds:
      user: laravel
    
      database: laravel
    config:
      databases:
        - laravel
      user: laravel
      
      default: laravel

  phpmyadmin:
    type: phpmyadmin
    ssl: true
    hosts:
      - database
    config:
      host: database
      user: laravel
    
      verbose: true